### ISSUE TITLE
`howdy-howdy` shows entries multiple times or not at all

### ISSUE THREAD

**Issue by glasserc** [punchagan/howdy#3]
Hi! Thanks for writing `howdy`, it seems like a clever way to get more organized when it comes to friends and family. I'm trying to integrate it into my workflow right now and encountering some strange behavior.

I've put `%%(howdy-howdy)` underneath a "Keep in touch" entry in my `contacts.org` file. But when I generate an agenda, I either see a person under every day, or not at all. For example, right now I have one contact with a `LAST_HOWDY` property set to three days ago. If I set `HOWDY_INTERVAL` to 4, then the contact doesn't show up in my agenda at all:

![screenshot from 2017-01-02 18-20-52](https://cloud.githubusercontent.com/assets/17006/21597385/39bc4d5e-d118-11e6-8e95-4f850a7c0139.png)

If I set `HOWDY_INTERVAL` to 3, then the contact shows up on every day:

![screenshot from 2017-01-02 18-21-51](https://cloud.githubusercontent.com/assets/17006/21597393/630b6b40-d118-11e6-8bee-6fa9236f24fc.png)

That seems confusing to me -- I'd expect to see the contact starting on the day when I would need to contact them again, or the first day after today if I should have contacted them earlier. Showing them on every day seems distracting and not more helpful.

Is it possible I'm using `howdy` wrong? Should I not be using a weekly agenda? It seems like `howdy-howdy` is getting called for every day of the agenda, which seems strange. I tried to investigate further but it seems like there's no mechanism whereby the date for the agenda is even exposed. Is this a limitation of the "diary-style sexp entries" that are explained in http://orgmode.org/manual/Weekly_002fdaily-agenda.html? Is there some other mechanism to use for generating agenda entries?

**Comment by punchagan** [comment]
@glasserc Thank you so much for trying out `howdy`.  You are probably the only other user, other than me.  Thanks for the detailed bug report and suggestions on expected behavior. I pushed a new commit to change this behavior similar to what you expect (and similar to how scheduled/deadline items seem to be shown in agendas) - on the current day of the agenda, all the backlog contacts are displayed, and on any other days, a contact that is becoming a backlog on that day is only shown.  

Feel free to reopen this issue, if this behavior doesn't match what you expect to happen.

**Comment by Niragjpatel** [comment]
i installed howdy and it fount it very useful, but agenda functin is not working,


i get this error

Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 3 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 4 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 5 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 6 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 7 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 8 2017)))) (howdy-howdy))
Bad sexp at line 2 in /Users/nirag/Dropbox/orgzly/network.org: (let ((entry ) (date (quote (7 9 2017)))) (howdy-howdy))


this is my setup,

* Keep in touch
%%(howdy-howdy)
** prakash
   :PROPERTIES:
   :HINTER:   3
   :EMAIL:    exam@pelle.com
   :LAST_HOWDY: [2017-07-02 Sun]
   :END:
** jk
   :PROPERTIES:
   :HINTER:   3
   :EMAIL:    jk
   :LAST_HOWDY: [2017-04-20 Thu]
   :END:

===== ===== ==  
kindly help
